includes:
  - from_url:
      url: jon4hz/meta/master/goreleaser.yml
  - from_url:
      url: jon4hz/meta/master/goreleaser-docker.yml

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh


variables:
  main: "./cmd/wishbox/main.go"
  binary_name: "wishbox"
  description: "wishlist using netbox as inventory source"
  github_url: "https://github.com/jon4hz/wishbox"
  maintainer: "jonah <me@jon4hz.io>"
  license: "MIT"
  homepage: "https://jon4hz.io"
  aur_package: |-
      # bin
      install -Dm755 "./wishbox" "${pkgdir}/usr/bin/wishbox"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/wishbox/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/wishbox.bash" "${pkgdir}/usr/share/bash-completion/completions/wishbox"
      install -Dm644 "./completions/wishbox.zsh" "${pkgdir}/usr/share/zsh/site-functions/_wishbox"
      install -Dm644 "./completions/wishbox.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/wishbox.fish"
      # man pages
      install -Dm644 "./manpages/wishbox.1.gz" "${pkgdir}/usr/share/man/man1/wishbox.1.gz"