version: "3.8"
services:
  wishbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./config.yml:/app/config.yml
      - .wishlist:/app/.wishlist
      - ./certs:/app/certs
    ports:
      - "2223:2223"
    