name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  goreleaser:
    uses: jon4hz/meta/.github/workflows/goreleaser.yml@master
    secrets:
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      AUR_KEY: ${{ secrets.AUR_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}